"""add new fields to StartupIdea

Revision ID: d05517d48a0f
Revises: 
Create Date: 2025-10-30 17:21:38.301542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05517d48a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_readiness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buzz_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('success_probability', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('investor_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('market_trend', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_ideas', schema=None) as batch_op:
        batch_op.drop_column('market_trend')
        batch_op.drop_column('investor_summary')
        batch_op.drop_column('success_probability')
        batch_op.drop_column('buzz_index')
        batch_op.drop_column('investor_readiness')

    # ### end Alembic commands ###
